export const BLOCKED_TERMS = [
  // Termos adultos
  'viagra',
  'porn',
  'xxx',
  'sex',
  'nude',
  'naked',
  'adult',
  'milf',
  'amateur',
  'fetish',
  'cam',
  'strip',
  'boobs',
  'ass',
  'fuck',
  'bitch',
  'slut',
  'whore',
  'prostitute',

  // Termos de apostas/jogos
  'casino',
  'poker',
  'betting',
  'gambling',
  'lottery',
  'slot',
  'roulette',
  'bet',
  'wager',
  'odds',
  'cialis',
  'levitra',
  'phentermine',
  'tramadol',
  'xanax',
  'valium',
  'adderall',
  'oxycodone',
  'hydrocodone',
  'prescription',
  'pharmacy',
  'pills',
  'medication',
  'drugs',

  // Termos financeiros suspeitos
  'loan',
  'credit',
  'debt',
  'mortgage',
  'insurance',
  'investment',
  'profit',
  'earn money',
  'make money',
  'quick cash',
  'easy money',
  'free money',
  'trading',
  'forex',
  'mlm',
  'pyramid',
  'ponzi',

  // Termos de spam gerais
  'click here',
  'buy now',
  'discount',
  'sale',
  'promotion',
  'winner',
  'congratulations',
  'prize',
  'gift',
  'free trial',
  'no cost',
  'guarantee',
  'refund',
  'instant',
  'urgent',
  'act now',
  'call now',
  'order now',

  // Termos violentos
  'kill',
  'murder',
  'suicide',
  'bomb',
  'terrorist',
  'violence',
  'weapon',
  'gun',
  'shoot',
  'attack',
  'threat',
  'hate',

  // Termos em português
  'porno',
  'sexo',
  'drogas',
  'aposta',
  'cassino',
  'empréstimo',
  'dinheiro fácil',
  'ganhe dinheiro',
  'remédio',
  'viagra',
  'compre já',
  'promoção',
  'desconto',
  'grátis',
  'prêmio',
  'sorteio',
  'loteria',
  'aposta',
  'jogo',
  'lucro',
  'ganho',
  'renda extra',
  'nude',
  'pelado',
  'pelada',
  'gostosa',
  'safada',
  'putinha',
  'vagabunda',
  'puta',
  'buceta',
  'pau',
  'pênis',
  'vagina',
  'anus',
  'cu',
  'merda',
  'caralho',
  'porra',
  'fdp',
  'viado',
  'bicha',
  'gay',
  'lésbica',
  'traveco',
  'trans',
  'matar',
  'morrer',
  'suicídio',
  'bomba',
  'terrorista',
  'violência',
  'arma',
  'tiro',
  'ataque',
  'ameaça',
  'ódio',
];

// Função para verificar se o texto contém termos bloqueados
export function containsBlockedTerms(text: string): boolean {
  const lowerText = text.toLowerCase();
  return BLOCKED_TERMS.some(term => {
    const lowerTerm = term.toLowerCase();
    // Verifica se o termo existe como palavra completa ou parte de uma palavra
    return lowerText.includes(lowerTerm);
  });
}

// Função para obter uma lista de termos encontrados (para debugging)
export function getFoundBlockedTerms(text: string): string[] {
  const lowerText = text.toLowerCase();
  return BLOCKED_TERMS.filter(term => {
    const lowerTerm = term.toLowerCase();
    return lowerText.includes(lowerTerm);
  });
}
