import type { PokemonDefinition } from './types';

export const STARTER_POKEMON: PokemonDefinition[] = [
  {
    id: 'bubbasaur',
    name: 'Bulbasaur',
    codename: 'Bulbasaur',
    typing: 'Grass / Poison',
    description: 'Germina energia solar e libera esporos que confundem bugs teimosos.',
    gender: 'masc',
    color: 'emerald',
    sprites: {
      front: '/pokemon/pokemons/bubbasaur/front-1.png',
      hover: '/pokemon/pokemons/bubbasaur/front-2.png',
      battle: [
        '/pokemon/pokemons/bubbasaur/battle-1.png',
        '/pokemon/pokemons/bubbasaur/battle-2.png',
      ],
    },
    stats: {
      hp: 45,
      attack: 49,
      defense: 49,
      specialAttack: 65,
      specialDefense: 65,
      speed: 45,
    },
    moves: [
      {
        name: 'Vine Whip',
        type: 'Grass',
        category: 'Physical',
        maxPp: 25,
        power: 45,
        description: 'Cipós chicoteiam o alvo em rápida sucessão.',
      },
      {
        name: 'Razor Leaf',
        type: 'Grass',
        category: 'Physical',
        maxPp: 25,
        power: 55,
        description: 'Folhas afiadas cortam com alta chance de acerto crítico.',
      },
      {
        name: 'Leech Seed',
        type: 'Status',
        category: 'Status',
        maxPp: 10,
        power: 0,
        description: 'Semeia o alvo e drena um pouco de energia a cada turno.',
      },
      {
        name: 'Solar Beam',
        type: 'Grass',
        category: 'Special',
        maxPp: 10,
        power: 120,
        description: 'Carrega energia e libera um feixe devastador.',
      },
    ],
  },
  {
    id: 'charmander',
    name: 'Charmander',
    codename: 'Charmander',
    typing: 'Fire',
    description: 'Acende deploys instantâneos e aquece qualquer revisão fria de código.',
    gender: 'masc',
    color: 'rose',
    sprites: {
      front: '/pokemon/pokemons/charmander/front-1.png',
      hover: '/pokemon/pokemons/charmander/front-2.png',
      battle: [
        '/pokemon/pokemons/charmander/battle%201.png',
        '/pokemon/pokemons/charmander/battle%202.png',
      ],
    },
    stats: {
      hp: 39,
      attack: 52,
      defense: 43,
      specialAttack: 60,
      specialDefense: 50,
      speed: 65,
    },
    moves: [
      {
        name: 'Ember',
        type: 'Fire',
        category: 'Special',
        maxPp: 25,
        power: 40,
        description: 'Uma chama pequena que pode deixar o alvo queimado.',
      },
      {
        name: 'Flame Burst',
        type: 'Fire',
        category: 'Special',
        maxPp: 15,
        power: 70,
        description: 'Explosão flamejante que danifica tudo ao redor do alvo.',
      },
      {
        name: 'Metal Claw',
        type: 'Normal',
        category: 'Physical',
        maxPp: 25,
        power: 50,
        description: 'Garras metálicas atacam e podem aumentar o ataque do usuário.',
      },
      {
        name: 'Smokescreen',
        type: 'Status',
        category: 'Status',
        maxPp: 20,
        power: 0,
        description: 'Nuvem de fumaça que reduz a precisão do oponente.',
      },
    ],
  },
  {
    id: 'squirtle',
    name: 'Squirtle',
    codename: 'Squirtle',
    typing: 'Water',
    description: 'Mantém pipelines frios e apaga qualquer incêndio em produção.',
    gender: 'fem',
    color: 'sky',
    sprites: {
      front: '/pokemon/pokemons/squirtle/front-1.png',
      hover: '/pokemon/pokemons/squirtle/front-2.png',
      battle: [
        '/pokemon/pokemons/squirtle/battle-1.png',
        '/pokemon/pokemons/squirtle/battle-2.png',
      ],
    },
    stats: {
      hp: 44,
      attack: 48,
      defense: 65,
      specialAttack: 50,
      specialDefense: 64,
      speed: 43,
    },
    moves: [
      {
        name: 'Water Gun',
        type: 'Water',
        category: 'Special',
        maxPp: 25,
        power: 40,
        description: 'Jato de água pressurizado diretamente no alvo.',
      },
      {
        name: 'Bubble Beam',
        type: 'Water',
        category: 'Special',
        maxPp: 20,
        power: 65,
        description: 'Corrente de bolhas que pode reduzir a velocidade do oponente.',
      },
      {
        name: 'Skull Bash',
        type: 'Normal',
        category: 'Physical',
        maxPp: 10,
        power: 130,
        description: 'Recolhe-se no casco e investe com uma cabeçada poderosa.',
      },
      {
        name: 'Withdraw',
        type: 'Status',
        category: 'Status',
        maxPp: 20,
        power: 0,
        description: 'Reforça a defesa ao se abrigar dentro do casco.',
      },
    ],
  },
];
